;
;.5841
; .db vibrato,20,1,254,255,4,  key_release,2,  vol_env,255,255,255,240,4,1,7,  tremolo_sub,2
; .db load_waveform,low(WF10),high(WF10),  pan_vol,14,15,  cntr0,2
;.585B
; .db cntr1,7
;.585D
; .db rest+6,  rest+6,  A4.,6,  rest+6  
; .db loop_1,low(.585D),high(.585D)
; .db rest+6,  rest+6,  C5.,6,  rest+6,  cntr1,6  
;.586C
; .db rest+6,  rest+6,  A4.,6,  rest+6  
; .db loop_1,low(.586C),high(.586C)
; .db rest+6,  rest+6,  D4.,6,  D4.,6,  D4.,6,  rest+6,  rest+6,  rest+6,  cntr1,3
;.5881
; .db rest+6,  rest+6,  D4.,6,  D4.,6,  F4.,6,  rest+6,  F4.,6,  rest+6,  rest+6,  rest+6
; .db D4.,6,  rest+6,  rest+6,  rest+6,  A4.,6,  rest+6
; .db loop_1,low(.5881),high(.5881)
; .db vol_env,255,255,0,240,4,0,10,  rest+12,  C4x,48,  C4x,6,  rest+6,  C4x,6,  rest+6
; .db C4x,6,  rest+6,  vol_env,255,255,255,240,4,1,7,  cntr1,2
;.58B8
; .db cntr2,8
;.58BA
; .db rest+6,  rest+6,  A4.,6,  rest+6
; .db loop_2,low(.58BA),high(.58BA)
; .db cntr2,4
;.58C4
; .db rest+6,  rest+6,  A4x,6,  rest+6
; .db loop_2,low(.58C4),high(.58C4)
; .db exit_1,low(.58DC),high(.58DC)
; .db cntr2,4
;.58D1
; .db rest+6,  rest+6,  C5x,6,  rest+6
; .db loop_2,low(.58D1),high(.58D1)
; .db loop_1,low(.58B8),high(.58B8)
;.58DC
; .db cntr1,3
;.58DE
; .db rest+6,  rest+6,  C5x,6,  rest+6
; .db loop_1,low(.58DE),high(.58DE)
; .db C5x,24,  rest+6,  rest+6,  D4.,6,  D4.,6,  F4.,6,  rest+6,  F4.,6,  rest+6,  rest+6
; .db rest+6,  D4.,6,  rest+6,  rest+6,  rest+6,  A4.,6,  rest+6,  rest+6,  rest+6,  D4.,6
; .db D4.,6,  F4x,6,  rest+6,  F4x,6,  rest+6,  rest+6,  rest+6,  D4.,6,  rest+6,  rest+6
; .db rest+6,  A4.,6,  rest+6,  rest+6,  rest+6,  E4.,6,  E4.,6,  G4.,6,  rest+6,  G4.,6
; .db rest+6,  rest+6,  rest+6,  E4.,6,  rest+6,  rest+6,  rest+6,  A4x,6,  rest+6,  rest+6
; .db rest+6,  C4x,6,  C4x,6,  E4.,6,  rest+6,  E4.,6,  rest+6,  rest+6,  rest+6,  E4.,6
; .db E4.,6,  E4.,6,  rest+6,  E4.,6,  rest+6,  rest+6,  rest+6,  D4.,6,  D4.,6,  F4.,6
; .db rest+6,  F4.,6,  rest+6,  rest+6,  rest+6,  D4.,6,  rest+6,  rest+6,  rest+6,  A4.,6
; .db rest+6,  rest+6,  rest+6,  D4.,6,  D4.,6,  F4.,6,  rest+6,  F4.,6,  rest+6,  rest+6
; .db rest+6,  D4.,6,  rest+6,  rest+6,  rest+6,  A4.,6,  rest+6,  rest+6,  rest+6,  E4.,6
; .db E4.,6,  G4.,6,  rest+6,  G4.,6,  rest+6,  rest+6,  rest+6,  E4.,6,  rest+6,  rest+6
; .db rest+6,  A4x,6,  rest+6,  rest+6,  rest+6,  C4x,6,  C4x,6,  E4.,6,  rest+6,  E4.,6
; .db rest+6,  rest+6,  rest+6,  E4.,6,  rest+6,  E4.,24
; .db loop_0,low(.585B),high(.585B)
; .db cntr0,2
;.599C
; .db cntr1,2  
;.599E
; .db rest+6,  rest+6,  D4.,6,  D4.,6,  F4.,6,  rest+6,  F4.,6,  rest+6,  rest+6,  rest+6
; .db D4.,6,  rest+6,  rest+6,  rest+6,  A4.,6,  rest+6
; .db loop_1,low(.599E),high(.599E)
; .db rest+6,  rest+6,  D4.,6,  D4.,6,  G4.,6,  rest+6,  G4.,6,  rest+6,  rest+6,  rest+6
; .db D4.,6,  rest+6,  rest+6,  rest+6,  A4x,6,  rest+6,  rest+6,  rest+6,  C4x,6,  C4x,6
; .db E4.,6,  rest+6,  E4.,6,  rest+6,  rest+6,  rest+6,  E4.,6,  rest+6,  E4.,24
; .db loop_0,low(.599C),high(.599C)
; .db cntr0,2
;.59E5
; .db cntr1,3  
;.59E7
; .db rest+6,  rest+6,  D4.,6,  D4.,6
; .db loop_1,low(.59E7),high(.59E7)
; .db D4.,12,  D4.,12,  cntr1,3
;.59F6
; .db rest+6,  rest+6,  E4.,6,  E4.,6
; .db loop_1,low(.59F6),high(.59F6)
; .db E4.,24
; .db loop_0,low(.59E5),high(.59E5)
; .db A4.,24,  A4.,24,  F4.,24,  F4.,24,  A4x,24,  A4x,24,  A4.,24,  A4.,24
; .db jump,low(.5841),high(.5841)
